### ISSUE TITLE
The ETH boards should configure themselves in runtime according to messages from robotInterface

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-firmware#15]
The EMS / MC4PLUS boards configure their services at startup according to their IP address. 

For instance, board EB1 which has IP address 10.0.1.1 configures itself to run motion control with 4 joints based on 2FOC boards and analog sensors STRAIN.

The CAN addresses, ports of AEA encoders, and nay other information is kept in FLASH.

However, it would be better that the EMS (MC4PLUS) could receive such information from robotInterface. The behaviour would be the following:
- for each device, robotInterface reads from an xml file the configuration that is needed by the ETH board;
- it sends it and waits an ACK from the ETH board;
- the ETH boards verifies if everything is available (for instance it checks if teh CAN boards are present or the encoders are working), it configures what is needed and sends an ACK;
- robotInterface continues the preparation of the device as it does now.
- At shutdown, robotInterface sends commands which de-init the ETH board.

**Comment by marcoaccame** [comment]
So far, I have implemented the STRAIN service.
Everything is on the runtime_ems_config branch with SHA: 7d945909120222c2c7711bf21ac14f759951647d and SHA: 3d15635a3ea9ba9a0abb62277d5f5489bc38a2ba 

There is not the full chain from robotInterface, though. I only have tested that everything is initted and de-initted properly with the very same data structure that robotInterface will send.

The EMS does that:
* uses datastructure to launch a can discovery of the strain can board,
* if KO it sends diagnostics, a KO message to robotInteraface and exit. Else, if OK:
* inits the analog-sensors endpoint to manage 1 strain.
* load in the CAN network 1 strain board and it inits the CAN protocol to address the strain object if can messages comes from that address
* it performs a full-scale request (which can be done again upon request of robotInterface),
* it sends back a OK to robotInterafce and waits for orders.
* if an order arrives it configures datarate and tx mode and enters in control-loop.

**Comment by marcoaccame** [comment]
Implemented the motion control service for foc-based and mc4-based motion control. Implemented also the MAIS service, used by this latter.
So far it is tested on desk bench the foc-based service with 1 joint only. 
I can now test the full board EB9 on the purple robot.

**Comment by marcoaccame** [comment]
It is high time to update this issue.

The two branches  runtime_ems_config (one for icub-firmware and one for icub-firmware-shared) have been merged into master on 11 jan 2016.

The result is an EMS application which is working apparently as before.

Every service now (for service I mean: motion control, skin, inertial analog sensors, strain analog sensor, mais analog sensor) is modeled by an object and can be started individually using a unified data structure modeled by `struct eOmn_serv_configuration_t`.  

Moreover, also the MC4PLUS application for the head V3 is made compliant to this paradigm.

For now the required data structure is retrieved from inside the FLASH of the board in a look-up table indexed by the IP address.

Next step is to implement the full run-time configuration as driven by robotInterface. 

However, now we need to stop some time in order to proceed with some other developments: the V3 and CER applications, which will be based on the same paradigm.

**Comment by barbalberto** [comment]
:+1:

**Comment by marcoaccame** [comment]
The FW of ETH boards (EMS, MC4PLUS, MC2PLUS) now supports runtime configuration (RTC) for all services apart from motion control.  

It means that when robotInterface loads a device of type embObjMais, embObjSkin, embObjStrain or embObjInertials, it sends all relevant configuration data to the ETH board which configures itself to offer the service.  As such, for instance, the CAN location of the STRAIN board is not embedded in the ETH board anymore but it is contained in an xml file.

For devices of type embObjMotionControl, robotInterface does not send yet the relevant configuration data, hence the ETH board retrieves it from FLASH according to its IP address.

This behavior has been operative on the rtc branches of icub-main, icub-firmware, and icub-firmware-shared for some time and was merged into master on 2 may 2016.

The RTC of motion control is not operative yet because we still need to: (1) wait for the merge into master of the new motion controller; (2) adjust its interfaces for RTC with consistent types; (2) define the format of xml files such as it contains the runtime configuration data of today (mapping of joint and encoders to the HW) but also the new data structure which generalize the control (joint set, coupling matrices, etc.).

@marcoaccame

**Comment by marcoaccame** [comment]
completed long ago
