### ISSUE TITLE
Fix building problem - MPLAB

### ISSUE THREAD

**Issue by giovannipizzolante** [robotology/icub-firmware#152]
When building the 2FOC.V3 project, the following error appears:

```../src/ecan.c:827:37: error: conflicting types for 'int8_t'```

 It is a problem related to the new compiler version. The old version contains this line:

https://github.com/robotology/icub-firmware/blob/b6c0a716bb75105fd1d62cfce6ae05c7d649df9b/emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/src/ecan.c#L827

that causes that error.

The fix is:

https://github.com/isorrentino/icub-firmware/blob/afd340abb343c5d5502970961266feaac327dd8a/emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/src/ecan.c#L1135

**Comment by GiulioRomualdi** [comment]
cc @marcoaccame @traversaro @isorrentino @nunoguedelha

**Comment by traversaro** [comment]
Which version of MPLAB are you using? Did you use the projects in the icub-firmware directly or you modified them in someway?
 
The problem seems due to the fact that there are two definitions of `int8_t`, and probably due to a newer version of the compiler/standard library the definition of `int8_t` changed from `char` to `signed char`, but the problem is that that typedef should not be there. Since C99, `int8_t` is defined in `stdint.h`, so it should be just sufficient to include that header.

**Comment by isorrentino** [comment]
>  Did you use the projects in the icub-firmware directly or you modified them in someway?

I just cloned the repo, imported the project in MPLAB and tried to compile it.


> Which version of MPLAB are you using?

- Product Version: MPLAB X IDE v5.40
- Compiler version: MPLAB XC16 Compiler v1.50

**Comment by traversaro** [comment]
Probably it make sense for reproducibility to mention somewhere in this repo or in https://github.com/robotology/icub-firmware-build which version of the MPLAB IDE/Compiler is used to generate the firmware. cc @marcoaccame @Nicogene @davidetome @ale-git

**Comment by marcoaccame** [comment]
the correct place where to put the compiler version used to generate the binary is in the log of the binary itself.
that already contains some basic info about how to reproduce the same binary, see [here](https://github.com/robotology/icub-firmware-build/commit/46d3f477b566be0b01d34409987e5d259abe36bb), and we could also add the version of the toolchain.

**Comment by isorrentino** [comment]
The PR has been merged. Closing.

**Comment by giovannipizzolante** [comment]
Sure @isorrentino . Closing the issue
