### ISSUE TITLE
implement I2T check in mc4plus fw

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-firmware#16]
For ems this check is done by 2foc

**Comment by davege89** [comment]
Same as #17.

**Comment by valegagge** [comment]
I implemented this check.

to be tested.

**Comment by valegagge** [comment]
I2T check is implemented in mc4plus firmware version 2.21, but it desn't run until I2T params ("motorPeackCurrent" and "motorNominalCurrent") are found out.

**Comment by valegagge** [comment]
Params have been found out in experimental way for macplus. (head and arm V3)
