### ISSUE TITLE
Find documentation on steps needed to build and flash motor boards (EMS, 2FOC)

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-firmware#161]
> This issue follows from https://github.com/dic-iit/lab-organisation/issues/148#issuecomment-770248640. I copy here the comment as I do not know if everybody has access.
> 
> > On Thursday I needed to build the firmware of the EMS board and I had to ask @marcoaccame for help. Only now I discover the existence of @nunoguedelha's comment in this issue in which all the steps necessary to properly configure the ide and the project are documented. I think that in the future someone else may need this guide, so it would make sense to put it somewhere that is more easily accessible, such as in the `README` of `icub-firmware` as @nunoguedelha also proposed.

[UPDATED]
I changed the title of the issue as this issue will include the issues @giulioromualdi and I experienced in testing a new firmware version. Basically, we needed to test this PR https://github.com/robotology/icub-firmware/pull/159 and @marcoaccame suggested me to build the code and then flash it on the boards and to avoid flashing the already compiled files uploaded in https://github.com/icub-tech-iit/task-force-miscellanea/issues/67#issuecomment-767574934.

**Steps I did and related documentation to know how to do each**
- Open the code in MPLAB and compile it. I did not find documentation about how to configure the environment (IDE and compiler). [This issue] (https://github.com/dic-iit/element_torque-control-via-current/issues/126#issuecomment-658288727) helped me in the past. I'll drop in a second comment the content of https://github.com/dic-iit/element_torque-control-via-current/issues/126#issuecomment-658288727.
- Modify the version of the firmware in [motor configuration files] (https://github.com/robotology/robots-configuration/blob/3a8e3f699cfaec5b7b5c07642801510b1e0ca683/iCubGenova09/hardware/motorControl/right_leg-eb10-j0_1-mc_service.xml#L22-L26).
- Flash the code by using the [script](https://github.com/robotology/icub-firmware-build/blob/master/scripts/FirmwareUpdater.script.update.all.foc.sh) provided in `icub-firmware-build` (I found the script my asking @marcoaccame in a call on teams)
- Build the EMS code. I did not find documentation on how to configure the environment (IDE and other required projects to compile before compiling the ems code). What copied in [this comment](https://github.com/robotology/icub-firmware/issues/161#issuecomment-770794804) helped me.
- I had to update to the last version `icub-firmware-shared` and I had to put it in the same folder of `icub-firmware` to be able to build the EMS code. 
- Once flashed the built EMS code the robot did not start. After one day I discovered that it was not starting as the `MC4PLUS` firmware was built with an old version of `icub-firmware-shared` and I needed to build also that one with the new version. So I needed to flash also that. 

I do not know if all these steps are documented somewhere but I did not find official documentation. I want to add that @marcoaccame helped me a lot in all the steps.

cc @marcoaccame @traversaro @DanielePucci @giulioromualdi @pattacini

**Comment by traversaro** [comment]
@isorrentino if there is already some material already available in that issue, I think the first step could be to copy it here so that anyone interested can clean it up and add it to the docs.

**Comment by isorrentino** [comment]
## Comments from https://github.com/dic-iit/lab-organisation/issues/148

- ### Nuno's comments
We are installing the development environment for the EMS board (ARM) from `Keil`, on Windows on the Monster machine.
Online link to the app: https://www.keil.com/demo/eval/arm.htm
Setup file location: `C:\Users\icub\Documents\ProgramInstallFiles\mdk528a.exe`
Install folder: `C:\Keil_v5`

How-to for the license activation: https://www.keil.com/product/brochures/readmefirst.pdf

**Note:** It is strongly recommended to accept the target install folder proposed by the installer, otherwise the activation phase will likely fail with the error message "TOOL.INI not installed".

Thanks @marcoaccame !!

I'm listing here the additional steps done by @marcoaccame for the installation of the IDE:

**download the `icub-firmware` and `icub-firmware-shared` repositories**

... downloaded into `C:\dev\git\embedded`.

**Download the `ipal-extra` libraries**

These libraries include a TCP/IP stack which is not open-source. Years ago it was stored in https://svn.icub.iit.local, but not anymore. So far it is only stored in our intranet: `\\storage05.icub.iit.local\repository\software\ipal-extra`. As a side note, the batch script `ipal-extra.install.bat` in `<code_root>\icub-firmware\emBODY\eBcode\arch-arm\libs\highlevel\abslayer\ipal` used to retrieve the files from the SVN repo, but now it just tells where to get the extra code.

- copy manually the files from folder `\\storage05.icub.iit.local\repository\software\ipal-extra` into the folder `C:\dev\git\embedded\icub-firmware\emBODY\eBcode\arch-arm\libs\highlevel\abslayer\ipal\ipal-extra`.

**Install the `ipal-extra` libraries**

- in that same folder `C:\dev\git\embedded\icub-firmware\emBODY\eBcode\arch-arm\libs\highlevel\abslayer\ipal`, double-click on `ipal.uvprojx`. This opens the `ipal` library project in the **uVision** IDE,
- build the project (F7).
- Now open the project `C:\dev\git\embedded\icub-firmware\emBODY\eBcode\arch-arm\board\ems004\appl\v2\proj\ems4rd.uvprojx` in the IDE (double-click on the file `ems4rd.uvprojx`), and build (F7).


- ### Marco's comment
the ipal-extra surely contains a TCP/IP stack which is not open-source.
years ago it was stored in https://svn.icub.iit.local, but not anymore. So far it is only stored in our intranet: `\\storage05.icub.iit.local\repository\software\ipal-extra`. the script file hence, dos not retrieve anymore and it just tells where to get the extra code.

**Comment by isorrentino** [comment]
### Content of https://github.com/dic-iit/element_torque-control-via-current/issues/126#issuecomment-658288727

#### Steps I followed to configure MPLAB and the compiler

> ## Installing the MPLAB X IDE
> 
> - Goto https://www.microchip.com/mplab/mplab-x-ide and browse down to "Downloads" section and download the latest version of MPLAB® X IDE driver for Windows (currently v5.40).
> - follow the instruction and default options
> 
> ## Installing the MPLAB XC Compilers
> 
> All the compilers and related dependencies can be downloaded from https://www.microchip.com/mplab/compilers, in the last section, in the tab "Compiler Downloads".
> ![image](https://user-images.githubusercontent.com/6848872/87525025-375ecb80-c689-11ea-9091-424cf2ab7e16.png)
> 
> The latest version for the compiler and dependencies on Windows is **v1.50**.
> 
> - After the install of the MPLAB X IDE is complete, follow the suggestion to download the "MPLAB XC compiler 16 bits" for dsPICs, and download the "MPLAB XC16 Compiler vX.XX" compiler for Windows, in "Compiler Downloads" tab (as shown above), "Compilers" subsection.
> - Launch the compiler installation: select the "free" option, and select the default options in the steps that follow.
> - Download Install the "MPLAB XC16 Compiler Part-Support Patch vX.XX" from the subsection "Latest Part Support Patch Files". This is a priori for supporting new parts, but actually the dsPIC used in our setup, version **33FJ128MC802**, appears in the "supported parts in the update" secttion of the [release notes of the patch](https://ww1.microchip.com/downloads/en/DeviceDoc/XC16-v1.50-part-support-release-notes.html).
> - Download Install the "Current Peripheral Libraries" -> "16-bit dsPIC33, PIC24E, PIC24H MCUs: Legacy Peripheral Libraries" from the subsection "Peripheral Libraries (PLIBS)" (latest version of "PIC24/dsPIC Peripheral Libraries v2.00 - Windows" [here](https://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en574967)).
> 
> ### Note on the "MPLAB XC16 Compiler vX.XX" compiler
> 
> The compiler "MPLAB XC16 Compiler v1.50" alone is missing some dependencies like the include `<pwm12.h>`. If you build the project without the mentioned additonnal patches, you'll get the error:
> ```
> CLEAN SUCCESSFUL (total time: 8ms)
> make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf
> make[1]: Entering directory 'C:/Users/icub/git/icub-firmware/emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/2FOC-V3.X'
> make  -f nbproject/Makefile-default.mk dist/default/production/2FOC-V3.X.production.hex
> make[2]: Entering directory 'C:/Users/icub/git/icub-firmware/emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/2FOC-V3.X'
> "C:\Program Files\Microchip\xc16\v1.50\bin\xc16-gcc.exe"   ../src/2FOC.c  -o build/default/production/_ext/1360937237/2FOC.o  -c -mcpu=33FJ128MC802  -MMD -MF "build/default/production/_ext/1360937237/2FOC.o.d"        -omf=elf -DXPRJ_default=default  -legacy-libc    -ffunction-sections -mlarge-data -O3 -I"../include" -msmart-io=1 -Wall -msfr-warn=off    -mdfp="C:/Program Files (x86)/Microchip/MPLABX/v5.40/packs/Microchip/dsPIC33F-GP-MC_DFP/1.2.35/xc16"
> "C:\Program Files\Microchip\xc16\v1.50\bin\xc16-gcc.exe"   ../src/DHES.c  -o build/default/production/_ext/1360937237/DHES.o  -c -mcpu=33FJ128MC802  -MMD -MF "build/default/production/_ext/1360937237/DHES.o.d"        -omf=elf -DXPRJ_default=default  -legacy-libc    -ffunction-sections -mlarge-data -O3 -I"../include" -msmart-io=1 -Wall -msfr-warn=off    -mdfp="C:/Program Files (x86)/Microchip/MPLABX/v5.40/packs/Microchip/dsPIC33F-GP-MC_DFP/1.2.35/xc16"
> "C:\Program Files\Microchip\xc16\v1.50\bin\xc16-gcc.exe"   ../asm/MeasCurr.s  -o build/default/production/_ext/1360919980/MeasCurr.o  -c -mcpu=33FJ128MC802  -omf=elf -DXPRJ_default=default  -legacy-libc  -I"../asm" -Wa,-MD,"build/default/production/_ext/1360919980/MeasCurr.o.d",--defsym=__MPLAB_BUILD=1,--no-relax  -mdfp="C:/Program Files (x86)/Microchip/MPLABX/v5.40/packs/Microchip/dsPIC33F-GP-MC_DFP/1.2.35/xc16"
> "C:\Program Files\Microchip\xc16\v1.50\bin\xc16-gcc.exe"   ../src/Faults.c  -o build/default/production/_ext/1360937237/Faults.o  -c -mcpu=33FJ128MC802  -MMD -MF "build/default/production/_ext/1360937237/Faults.o.d"        -omf=elf -DXPRJ_default=default  -legacy-libc    -ffunction-sections -mlarge-data -O3 -I"../include" -msmart-io=1 -Wall -msfr-warn=off    -mdfp="C:/Program Files (x86)/Microchip/MPLABX/v5.40/packs/Microchip/dsPIC33F-GP-MC_DFP/1.2.35/xc16"
> "C:\Program Files\Microchip\xc16\v1.50\bin\xc16-gcc.exe"   ../src/PWM.c  -o build/default/production/_ext/1360937237/PWM.o  -c -mcpu=33FJ128MC802  -MMD -MF "build/default/production/_ext/1360937237/PWM.o.d"        -omf=elf -DXPRJ_default=default  -legacy-libc    -ffunction-sections -mlarge-data -O3 -I"../include" -msmart-io=1 -Wall -msfr-warn=off    -mdfp="C:/Program Files (x86)/Microchip/MPLABX/v5.40/packs/Microchip/dsPIC33F-GP-MC_DFP/1.2.35/xc16"
> "C:\Program Files\Microchip\xc16\v1.50\bin\xc16-gcc.exe"   ../src/ADC.c  -o build/default/production/_ext/1360937237/ADC.o  -c -mcpu=33FJ128MC802  -MMD -MF "build/default/production/_ext/1360937237/ADC.o.d"        -omf=elf -DXPRJ_default=default  -legacy-libc    -ffunction-sections -mlarge-data -O3 -I"../include" -msmart-io=1 -Wall -msfr-warn=off    -mdfp="C:/Program Files (x86)/Microchip/MPLABX/v5.40/packs/Microchip/dsPIC33F-GP-MC_DFP/1.2.35/xc16"
> "C:\Program Files\Microchip\xc16\v1.50\bin\xc16-gcc.exe"   ../src/System.c  -o build/default/production/_ext/1360937237/System.o  -c -mcpu=33FJ128MC802  -MMD -MF "build/default/production/_ext/1360937237/System.o.d"        -omf=elf -DXPRJ_default=default  -legacy-libc    -ffunction-sections -mlarge-data -O3 -I"../include" -msmart-io=1 -Wall -msfr-warn=off    -mdfp="C:/Program Files (x86)/Microchip/MPLABX/v5.40/packs/Microchip/dsPIC33F-GP-MC_DFP/1.2.35/xc16"
> "C:\Program Files\Microchip\xc16\v1.50\bin\xc16-gcc.exe"   ../src/DCLink.c  -o build/default/production/_ext/1360937237/DCLink.o  -c -mcpu=33FJ128MC802  -MMD -MF "build/default/production/_ext/1360937237/DCLink.o.d"        -omf=elf -DXPRJ_default=default  -legacy-libc    -ffunction-sections -mlarge-data -O3 -I"../include" -msmart-io=1 -Wall -msfr-warn=off    -mdfp="C:/Program Files (x86)/Microchip/MPLABX/v5.40/packs/Microchip/dsPIC33F-GP-MC_DFP/1.2.35/xc16"
> "C:\Program Files\Microchip\xc16\v1.50\bin\xc16-gcc.exe"   ../src/can_icubProto.c  -o build/default/production/_ext/1360937237/can_icubProto.o  -c -mcpu=33FJ128MC802  -MMD -MF "build/default/production/_ext/1360937237/can_icubProto.o.d"        -omf=elf -DXPRJ_default=default  -legacy-libc    -ffunction-sections -mlarge-data -O3 -I"../include" -msmart-io=1 -Wall -msfr-warn=off    -mdfp="C:/Program Files (x86)/Microchip/MPLABX/v5.40/packs/Microchip/dsPIC33F-GP-MC_DFP/1.2.35/xc16"
> Options have been disabled due to restricted license
> Visit https://www.microchip.com/compilers to purchase a new key.
> In file included from ../src/Faults.c:5:0:
> ../include/PWM.h:10:19: fatal error: pwm12.h: No such file or directory
> compilation terminated.
> ```
> This is a known issue with the latest drivers released after version **v1.24**. The fast workaround in the previous setup was to revert the driver back to version 1.24. That version should be available in https://www.microchip.com/development-tools/pic-and-dspic-downloads-archive, but does not clearly appear in section "MPLAB C Compiler for PIC24 and dsPIC DSCs" and seems to be available only as "Source Archives". The real cause of the issue is actually explained in the [v1.25 release notes](http://ww1.microchip.com/downloads/en/DeviceDoc/XC16-v-1.25%20release%20notes.html):
> ```
> The peripheral libraries are no longer shipped with the compiler package. These may be downloaded separately from the MPLAB XC download page.
> ```
> So, the proper fix is to download the additional Legacy Peripheral Libraries as explained int the previous section.
> 
> ## Running the MPLAB X IDE [WIP]
> 
> - Run app MPLAB X IDE v5.40.
> - Open the project [2FOC-V3.X](https://github.com/robotology/icub-firmware/tree/master/emBODY/eBcode/arch-dspic/board/2foc/appl/2FOC-V3/2FOC-V3.X) (shortcut CTRL+SHIFT+O on windows).
> - you should see in the lower left pane:
> 
> ![image](https://user-images.githubusercontent.com/6848872/87447680-27000f80-c5fb-11ea-9ce9-93ad20d500d0.png)
> 
> The 2FOC device is the **dsPIC33FJ128MC802**.
> - Then click on Packs - dsPIC33F-GP-...   You should see a popup window with the project properties
> 
> ![image](https://user-images.githubusercontent.com/6848872/87448059-9e35a380-c5fb-11ea-8da8-322ee21663c4.png)
> 
> just click "OK".
> - Clean and Build the project as shown below:
> <img width="1751" alt="image" src="https://user-images.githubusercontent.com/6848872/87537294-b01a5380-c69a-11ea-96a3-7ab9866dd1d2.png">

**Comment by isorrentino** [comment]
I modified the title of the issue and I summarized the aim in the first comment https://github.com/robotology/icub-firmware/issues/161#issue-797494427.

cc @traversaro @pattacini @maggia80 @marcoaccame @ale-git @DanielePucci @giulioromualdi

**Comment by pattacini** [comment]
Thanks @isorrentino for this contribution!

I believe we would should integrate this material into our official documentation at https://icub-tech-iit.github.io/documentation.

cc @marcoaccame

**Comment by traversaro** [comment]
fyi @AlexAntn

**Comment by pattacini** [comment]
We will be dealing with this next sprint.

**Comment by traversaro** [comment]
Related PR: https://github.com/icub-tech-iit/documentation/pull/90 . cc @AlexAntn @isorrentino

**Comment by pattacini** [comment]
Documentation ready at See https://icub-tech-iit.github.io/documentation/icub_firmware/fw_toolchain ✔

**Comment by pattacini** [comment]
Closing, feel free to open it up again if needed.
