### ISSUE TITLE
Document data types 2FOC

### ISSUE THREAD

**Issue by giovannipizzolante** [robotology/icub-firmware#190]
By looking at the documentation of the XC compiler 16 (https://ww1.microchip.com/downloads/en/DeviceDoc/MPLAB_XC16_C_Compiler_Users_Guide_50002071L.pdf), me and @GiulioRomualdi noticed that the `short` data types seems to be 2 bytes long as the `int` data type. As shown in the following table. 

![Datatypes](https://user-images.githubusercontent.com/72971613/122082882-a7795280-ce00-11eb-9575-dce6e960187e.PNG)

Is this correct? Furthermore, is this the correct documentation?

**Comment by pattacini** [comment]
cc @ale-git

**Comment by ale-git** [comment]
Yes, it is correct: the **int** type is 16 bit.

**Comment by giovannipizzolante** [comment]
and the **short** type?

**Comment by ale-git** [comment]
The same, 16 bit like in your table.

**Comment by GiulioRomualdi** [comment]
cc @isorrentino

**Comment by giovannipizzolante** [comment]
The User's Guide in the first comment is wrong. The correct one is this one:

[User'sGuide.pdf](https://github.com/robotology/icub-firmware/files/6763434/User.sGuide.pdf)

cc @isorrentino
