### ISSUE TITLE
Use new fields in joint.status.ofpid

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-firmware#37]
After activity of issue #34, there is a new definition for the status of the joint.

In particular, the status of the PID has been enlarged to define multiple references and errors. The status is modeled with a union whose fields are used depending on control mode and interaction mode. 

So far, icub-main and FW use the `legacy` field, but it is required to use the new fields.

Can please @valegagge deal with the icub-main part and @davege89 deal with the FW part?

I will be happy offer support to both of you.

**Comment by davege89** [comment]
This has been accomplished since EMS application version 2.18 (robotology/icub-firmware-build@2c3f6c4d67875f99e4ed8b6c800ae2d70d5e29ef).
Closing.
