### ISSUE TITLE
New Can-Loader/ETH-Loader tool (qt version)

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-firmware#39]
should include also command line option for all possible commands, so it can be included in bash scripts.

**Comment by randaz81** [comment]
See also feature request:
https://github.com/robotology/icub-firmware/issues/38

**Comment by traversaro** [comment]
I don't know if "can be included in bash scripts" means that, but it would be extremly convenient to have the [`updateRobot.sh`](https://github.com/robotology/icub-firmware-build/blob/master/updateRobot.sh) script to work also on ETH robots.

**Comment by marcoaccame** [comment]
implemented in icub-firmware-build\scripts
