### ISSUE TITLE
Fix bug on 2foc ver 3.6 related to the encoder readings

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-firmware#427]
On ergocub 1.1 we experienced a block of the motor of the right shoulder pitch when it goes down with high velocity.

Here the reference: https://github.com/icub-tech-iit/proto/issues/2530#issuecomment-1768444629

**Dod**
bug fixed

**Comment by maggia80** [comment]
today @AntonioConsilvio tested the legs with the same firmware and he managed to replicate the same issue on the `left or right ankle roll`

**Comment by valegagge** [comment]
After a chat with  @AntonioConsilvio, he noticed that the current consumed is around 12A (read in the yarpmotorgui). He stopped the joint before it could go into fault. 
In order to exit from this situation, he had to move by hand the joint of about 10 deg.

**Comment by ale-git** [comment]
The high current depends - very likely - on the loss of rotor angle measurement: if the motor torque drops because of lack of synchronization between rotor and stator field, the controller increases the current without effectiveness.

**Comment by ale-git** [comment]
Comparing the 3.3 and 3.6 firmware I noticed that there is a difference in the encoder index signal front reading, that is configurable.

![image](https://github.com/robotology/icub-firmware/assets/4729270/f4cadedd-d0b7-49a6-8db7-551dbc9e63f7)

The IMV bits have always been set to `11` for iCub ROIE motor encoders but, while testing the new ErgoCub joint with MRIE encoders, I noticed that some index detection were missing when the motor was rotating clockwise and thus, after some tries, I found that the problem was solved by changing the configuration to `10`.
So: in the 3.3 firmware IMV="11", while in the 3.6 firmware IMV="10".

Now, we see that the 3.6 firmware has problems with the lecture of the index in one direction with the old ROIE encoders, so I suspect that it is due to the IMV configuration made for MRIE encoders. I prepared a 3.6 firmware with IMV="11" in order to check if it solves the issue. In this case we have to make the IMV control bits configrable at runtime. The motor configuration CAN message use one byte for the number of polar couples of the motor that seems eccessive, so we can change the protocol so that 2 bits are used for IMV configuration and 6 bits are used for polar couples (at present the maximum number of polar couples is 20 and it is unlike that it can excess 62).

**Comment by maggia80** [comment]
MRIE is equipped with AEDR-9830

<img width="877" alt="image" src="https://github.com/robotology/icub-firmware/assets/6987330/77f9bcf7-ed30-49b8-b45f-a25dada12086">

The index phase in the MRIE is set in the board and it's 180:  

<img width="679" alt="image" src="https://github.com/robotology/icub-firmware/assets/6987330/d37fcda3-951b-4a07-b1bd-6dcc48f2a283">

and 
<img width="884" alt="image" src="https://github.com/robotology/icub-firmware/assets/6987330/854382be-bbce-401e-b0db-c00697cba59f">


LCORE with AEDR-8501-102

<img width="992" alt="image" src="https://github.com/robotology/icub-firmware/assets/6987330/78f7af6a-9ebd-4281-814d-a421e606f5ea">

Index phase for the LCORE is set in the chip and it's 180 degree ->
<img width="459" alt="image" src="https://github.com/robotology/icub-firmware/assets/6987330/4bbdaef7-77f6-4c4e-806c-d56c7b988861">

**Comment by maggia80** [comment]
the connectors have same pinout: 

MRIE connector is:

<img width="513" alt="image" src="https://github.com/robotology/icub-firmware/assets/6987330/1096e8cb-2336-46bc-8b5e-ea0f71115511">


and LCORE:

<img width="449" alt="image" src="https://github.com/robotology/icub-firmware/assets/6987330/c06319f0-da1f-4aec-92b8-554084d4e975">

**Comment by maggia80** [comment]
> Comparing the 3.3 and 3.6 firmware I noticed that there is a difference in the encoder index signal front reading, that is configurable.
> 
> ![image](https://user-images.githubusercontent.com/4729270/280240433-f4cadedd-d0b7-49a6-8db7-551dbc9e63f7.png)
> 
> The IMV bits have always been set to `11` for iCub ROIE motor encoders but, while testing the new ErgoCub joint with MRIE encoders, I noticed that some index detection were missing when the motor was rotating clockwise and thus, after some tries, I found that the problem was solved by changing the configuration to `10`. So: in the 3.3 firmware IMV="11", while in the 3.6 firmware IMV="10".
> 
> Now, we see that the 3.6 firmware has problems with the lecture of the index in one direction with the old ROIE encoders, so I suspect that it is due to the IMV configuration made for MRIE encoders. I prepared a 3.6 firmware with IMV="11" in order to check if it solves the issue. In this case we have to make the IMV control bits configrable at runtime. The motor configuration CAN message use one byte for the number of polar couples of the motor that seems eccessive, so we can change the protocol so that 2 bits are used for IMV configuration and 6 bits are used for polar couples (at present the maximum number of polar couples is 20 and it is unlike that it can excess 62).

MRIE has the index associated to CHB, while LCORE to CHA. That's why you need to change the IMV register

**Comment by maggia80** [comment]
however, having the phase to 180 degrees, there is something that does not sound to me. With 180 the state of phase A and B when the Quadrature is x4 is not defined!

In case of the MRIE, CHA has a transaction from 1 to 0, while CHB is fixed to 1.
for LCORE, CHA is fixed to 1, while CHB has a transaction from 0 to 1.

**Comment by ale-git** [comment]
> however, having the phase to 180 degrees, there is something that does not sound to me. With 180 the state of phase A and B when the Quadrature is x4 is not defined!
> 
> In case of the MRIE, CHA has a transaction from 1 to 0, while CHB is fixed to 1. for LCORE, CHA is fixed to 1, while CHB has a transaction from 0 to 1.

I don't understand this part, maybe you can explain it to me face to face next week at CRIS?

**Comment by maggia80** [comment]
this is the case of the LCORE <img width="1401" alt="image" src="https://github.com/robotology/icub-firmware/assets/6987330/de42fb10-b283-4f5c-942d-72d44a6ff789">

**Comment by maggia80** [comment]
and this is the MRIE: 
<img width="1299" alt="image" src="https://github.com/robotology/icub-firmware/assets/6987330/af686a8c-ec07-4cd2-b873-344a5fe4b00a">

**Comment by ale-git** [comment]
This is the 3.3 version with MRIE Index configuration.
[2FOC-V3.3.MRIE.zip](https://github.com/robotology/icub-firmware/files/13254325/2FOC-V3.3.MRIE.zip)

**Comment by valegagge** [comment]
Hi @ale-git ,
this isn't the correct issue where attach the exe. please see this [comment](https://github.com/icub-tech-iit/ergocub-design-joint/issues/179#issuecomment-1792835172).

Anyway I already moved the .zip file. 😸

**Comment by valegagge** [comment]
We decided do not to use the 2foc fw ver3.6
