### ISSUE TITLE
Implement hard stop calibration, AMO-less operation in Ergocub 

### ISSUE THREAD

**Issue by ale-git** [robotology/icub-firmware#435]
At present the Ergocub and iCub 3 robots use AMO angular position sensors as incremental encoders as a workaround to avoid the absolute position loss problem. This requires hard stop calibration that has been implemented some time ago. Now we want be able to run a joint without the AMO sensor, only relying onto the motor encoder, in case of complete AMO sensor breakage. Some modifications are thus required to synchronize the EMS and the 2FOC boards at startup, in this order:
1) the 2FOC runs its own calibration (encoder Index calibration, current sensor calibration)
2) the EMS performs hard stop calibration of the joint

Definition of Done:

 New EMS firmware tested and merged.

@valegagge

**Comment by valegagge** [comment]
Hi @ale-git,
to achieve this goal we don't need to change the 2foc fw, do we?

**Comment by ale-git** [comment]
No, it has no dependecy.

**Comment by ale-git** [comment]
I've tested the fw on Ergocub 1.1 and it works properly.

**Comment by valegagge** [comment]
PR opened here: https://github.com/robotology/icub-firmware/pull/438.

**Comment by valegagge** [comment]
## add this feature in the new sw-distro: 
![image](https://github.com/robotology/icub-firmware/assets/4233231/e1781019-035d-4393-85c6-9c98a558ae65)

**Comment by valegagge** [comment]
Dod satified. Closing
