### ISSUE TITLE
Validate the q_enc reading improvement on the ergocub 1.X joints

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-firmware#446]
# Task
During the test on ergocub 2.0 joints, we noticed that the index interrupt service routine can be executed with a big delay that is used to disrupt the FOC control at motor high speed. So we changed the position counter reset policy from software (on interrupt) to hardware (managed by the QE peripheral of the dspic33f). 

This change solved the problem on the ergocub joints 2.0.
Now we want to perform the same test on the ergocub 1.x joints

# Dod
- [x] Test done
- [x] Data collected and reported here. 
- [x] Collect the same data on ergocub 2.0 and put here the report.

For collecting data, please perform the same tests [here](https://github.com/icub-tech-iit/ergocub-design-joint/issues/179#issuecomment-1802128164).

**Comment by valegagge** [comment]
Here I report the tests done on the **small joint on ergocub 2.0** highlighting the difference between running the joint with the official fw version and with the bug fixed.
![image](https://github.com/robotology/icub-firmware/assets/4233231/c07449b3-0bc6-41a1-b19b-726c89b8e259)

**Comment by valegagge** [comment]
Here I report the tests done on the **torso pitch joint of ergocub 1.x** highlighting the difference between running the joint with the official fw version and with the bug fixed.

![image](https://github.com/robotology/icub-firmware/assets/4233231/16429c93-47c0-4544-bfef-9907ea2dd235)

**Comment by valegagge** [comment]
cc @maggia80

**Comment by maggia80** [comment]
These are amazing results!!! This means a big improvement in the performance/efficiency of our robots!

**Comment by valegagge** [comment]
dod satisfied. Closing
