### ISSUE TITLE
hal2.stm32f4.uvprojx doesn't compile with Keil compiler version 6

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-firmware#465]
I noticed that `hal2.stm32f4.uvprojx` compiles only with the compiler v5, while it returns 87 errors (due to cmsis) with the compiler  v6.

Do we need to update the project?

cc @marcoaccame @sgiraz

**Comment by sgiraz** [comment]
\remind 12th Feb (cc @marcoaccame)

**Comment by marcoaccame** [comment]
There is no need to change the project because the `hal2.stm32f4` uses ST Microelectronics code that is not compatible w/ compiler v6, so we need to stay w/ the v5 for it.

**Comment by valegagge** [comment]
so we can close this issue.

thanks @marcoaccame
