### ISSUE TITLE
torque at 32 bit resolution

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-firmware#47]
@DanielePucci has requested to have torque represented w/ 32 bit resolution instead of as a int16_t with 1 milliNm per unit so that we can manage torques of more than 32 Nm.

**Comment by marcoaccame** [comment]
done `torque32bits` branches in icub-main, icub-firmware-shared, icub-firmware. added in `master` a icub-firmware-buld/testing/ems-torque32bits.hex w/ version 222.20

tested on purple robot. basic movement seems to be working. 

@DanielePucci can you please verify it it is OK also the torque control?

**Comment by ale-git** [comment]
@marcoaccame In the axisController the torques are already represented with int32, but the torque measure setting function eo_axisController_SetTorque was still 16 bit, did you change it?

**Comment by DanielePucci** [comment]
As we discussed today, further investigations deserved to be carried on to clarify the soundness of measured and reference torques coming from robotInterface. Then, tests on the new representations will also be preformed. @francesco-romano @traversaro

**Comment by marcoaccame** [comment]
Yes @ale-git, I have changed it into:
```C
extern void eo_axisController_SetTorque(EOaxisController *o, eOmeas_torque_t trq)
```

**Comment by marcoaccame** [comment]
tested again on iCubGenova02 and merged into master.
