### ISSUE TITLE
timing in control loop should be tunable

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-firmware#50]
In https://github.com/robotology/icub-support/issues/130#issuecomment-161992374 it was reported a:

`Warning on "timing overflow on some phases of the control Loop on EMS" (arms)`.

The reason of that may be due to the fact that the boards in forearm (EB2/EB4) have 12 joints to manage and in some control situations they must send many CAN frames all together.

The control loop sends the CAN frames in its TX phase  and waits until all frames are transmitted.

For all boards, the time allocated for this TX phase is 300 usec. The timing for all the phases are: RX-DO-TX = 400-300-300.

However some boards such as the EB2/EB4 do not need time in the DO phase.

In order to reduce the execution overflow in TX phase it would be useful to allocate timings in a dedicated way.

**Comment by marcoaccame** [comment]
I have added the possibility to configure in runtime the timing for the control-loop, provided that it is not running (i.e., we are in CFG state and not in RUN).

Now the boards which behave as CAN gateway and dont have a local motion control activity (EB2/4/10/11) have the following timing.

`RX-DO-TX = 450-050-500`

All others have timing:

`RX-DO-TX = 400-300-300`

I have produced a new EMS fw version v2.21 which should be tested in the same conditions as in https://github.com/robotology/icub-support/issues/130#issuecomment-161992374.

Please @francesco-romano can you help me test it?

**Comment by marcoaccame** [comment]
I attach a piece of a log file w/ timing of control loop which exceed the TX time of 300 usec. The file comes from @francesco-romano and was taken with a FW release older than v2.21.

It appears that the TX phase lasted even more than 500 usec: 736, 1070, etc.

As the `RX-DO-TX = 450-050-500` newly tuned timings cannot handle these numbers, we close the issue.

As there is a suspect that the extra time comes for some reason, either much CAN frames to be transmitted or some (many) occasional ROPs are sent (for instance due to the proxy), we add some more info on error code 0x0000000d. For now we add the number of TX CAN frames, later on we shall add number of occasional ROPs.

In such a way we know why there is this extra time. 



[log_robotInterface_forearm_warnings.txt](https://github.com/robotology/icub-firmware/files/61276/log_robotInterface_forearm_warnings.txt)

**Comment by DanielePucci** [comment]
:+1:
