### ISSUE TITLE
Test on the robot of new features and bugfix for calibration type 10 for AMO encoder

### ISSUE THREAD

**Issue by MSECode** [robotology/icub-firmware#537]
In this issue we are going to add the outcomes of the tests on the robot for the enhancements and bugfixes done to the calibration type 10 process discussed in the following issues:
- https://github.com/icub-tech-iit/study-encoders/issues/31
- https://github.com/robotology/icub-firmware/issues/529

**Comment by MSECode** [comment]
### Tests have been done on `ergoCubSN000`
First of all I'd like to report the status I found the robot, so that if any error happens we can recover from the repos I've rebased:

- superbuild
![Image](https://github.com/user-attachments/assets/836cd8a2-ab22-4594-9e0b-335fc981dbf0)

- icub_firmware_shared
![Image](https://github.com/user-attachments/assets/528c551b-19a2-45bf-a58d-80e86ccb7433)

- ICUB
![Image](https://github.com/user-attachments/assets/21ad956b-2a5b-4885-8197-00a2407715ac)

- YCM
![Image](https://github.com/user-attachments/assets/cfab2709-c06a-481e-8814-badf5fc0c2e4)

- YARP
![Image](https://github.com/user-attachments/assets/08f280aa-fd0e-4da7-b272-8a898820d426)
 
- icub-firmware-build
![Image](https://github.com/user-attachments/assets/4e2ba723-4c1e-44cb-9ac3-131ac7b88f8c)


#### First step updating of the `robotology-superbuild`

Everything oks. I moved the repos as follows:
- robotology-superbuild --> pulled from latest master
- icub-firmware-shared --> pulled latest devel
- ICUB --> pulled latest devel
- YCM --> last tag v0.17.1
- YARP --> last tag v3.10.1

**Comment by valegagge** [comment]
Hi @MSECode, 
well done! Thanks for also reporting the previous state of the robot and the state after the update. 🚀 Since you didn't get errors to can proceed to create the PRs.

**Comment by MSECode** [comment]
PRs opened and linked all to this one: https://github.com/robotology/icub-firmware-build/pull/174
