### ISSUE TITLE
Implement the get-fw-version can message in MTB boards

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-firmware#7]
It is important to have this message, so that one can launch a discovery procedure to check presence of a list of MTB board before attempting using them.

**Comment by marcoaccame** [comment]
tested the new fw from @valegagge with the get-fw-version. it works. 
i suggest using an increased minor version number (2.17 build 0) and to commit sources.
the binary should then be committed following what in robotology/icub-firmware-build#3

**Comment by valegagge** [comment]
Done.
commited source with sha 7f54995cafae1c6e55b4558b48fa01eeeb1a9a85.
commited exe in firmware  robotology/icub-firmware-build with sha 2938b868cb101bf8d741714e233c34294b133b8e
