### ISSUE TITLE
Add current limit in order to limit torque on motor

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-firmware#73]
The purpose of this limit is to avoid motor damages. If instantaneous current exceeds the limit, the joint will be not put in hardware fault

**Comment by valegagge** [comment]
Done. We implemented the check of current limits in firmware.

The user can configure the value of limit in xml file and the firmware performs both I2T and current overload (instantaneous peak) checks.

**Comment by traversaro** [comment]
>  If instantaneous current exceeds the limit, the joint will be not put in hardware fault

will be put or will be **not** put in hardware fault? 
Is this changing the behavior of our robots? 
cc @S-Dafarra @diegoferigo @gabrielenava
