### ISSUE TITLE
MC4PLUS - external fault status

### ISSUE THREAD

**Issue by davidetome** [robotology/icub-firmware#79]
If I press the fault button once the mc4plus remains in the fault status until I reset the boards (usually power off - power on) that takes a lot of seconds to wait before you can run yarprobotinterface again.
It should be nice if , every time yarprobotinterface starts, mc4plus checks the actual fault button status. 
@valegagge

**Comment by valegagge** [comment]
Fixed.
You can use fw MC4PLUS 2.48 on master branch.

I merged this patch in devel branch also.
