### ISSUE TITLE
Migrate FW projects for MAIS, STRAIN, MTB into MPLAB-X

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-firmware#8]
It is important to migrate to the new tool-chain as experience shows it it much more user-friendly.

**Comment by marcoaccame** [comment]
there are two available licences for mplab-x which can be requested to @mbrunettini. @valegagge can ask help to @ale-git who has already the 2foc application on mplab-x

**Comment by valegagge** [comment]
I added mplabX project files for strain and mais application on master branch. 
(see 587862a78745c7e3b005a9d89da73b50795e08fa and 70db9e71032f6e08ccc8cbdd9f8158202a2e1081 )

I used MplabX ide v3.35 and compiler Mplab c30 ver 3.31.
Note that the compiler is the same used in mplab, so the executable should be the same.
Before using executable compiled with new ide, i would like test it on a robot, but currently there is no one in lab.

**Comment by valegagge** [comment]
Also added Mplabx project files form mtb.

**Comment by valegagge** [comment]
I flashed strain, mais and skin firmware compiled with MPLABX ide on purple iCub.
 - Strain version is 3.0.6
 - Mais version is 3.1.3
 - Skin version  is 2.17.1
The executables are here: icub-firmware-build@132f49a78b2a15d01c64706680c629291a77f70c

If in a few days no error occurs, I'll release these new versions.

**Comment by valegagge** [comment]
No error occured, so I moved the executables in master branch.
