### ISSUE TITLE
Correct the information on the Can-protocol official document

### ISSUE THREAD

**Issue by Gianlucamilani** [robotology/icub-firmware#92]
In the pdf document TSD-ICUBUNIT-canprotocol-sensorboards, which describes the canprotocol used by icub and which is useful for us in the context of #81 , the information at page 116 about LSB-Z is missing and has to be added. The document is downloadable at the following [link](https://github.com/robotology/icub-firmware/blob/devel/emBODY/eBdocs/arch-arm/TSD-ICUBUNIT-canprotocol-sensorboards.docx).

@marcoaccame when you are available we can talk about this

**Comment by marcoaccame** [comment]
sure @Gianlucamilani: i will get to to today

**Comment by marcoaccame** [comment]
Corrected
